GET http://localhost:5000/category/5ec5fe00b13b45c9c3b5f40d
Accept: application/json

###
GET http://localhost:5000/category
Accept: application/json

###
POST http://localhost:5000/category
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

test3
--WebAppBoundary
Content-Disposition: form-data; name="description"

test
--WebAppBoundary

###
